### ISSUE TITLE
Invoke Aspects in multi module project

### ISSUE THREAD

**Issue by sheelaknaik** [Archinamon/android-gradle-aspectj#89]
Hi,

Does this plugin support weaving aspects in a multi module project? For example, if the modules in the project are libraries, how can we weave our aspects in those modules too? Currently, I see it working at app level only.

Please suggest.

**Comment by Archinamon** [comment]
Hello!
Sorry for late answer. If your aspects live in app module, it will have access to all your local modules due to appearing them in android's transformation stream and in classpath. It should work without any workarounds. But I did not test it this way, please try it in the simpliest way :)

If it won't. You can simply add in config closure in build.gradle parameter `includeJar` describing your sub-modules you want to augment with aspects.

**Comment by sheelaknaik** [comment]
Thanks @Archinamon , it solves the issue
